# Generated by Django 5.1.4 on 2024-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_employees', models.PositiveIntegerField()),
                ('enquiry_message', models.TextField()),
                ('plan_name', models.CharField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Small Business', 'Small Business'), ('Corporate', 'Corporate'), ('Custom', 'Custom')], max_length=50)),
                ('plan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
            ],
        ),
    ]
